### ISSUE TITLE
@damianpumar CMA

### ISSUE THREAD

**Issue by damianpumar** [nimble-ui/community#2]
Hi! my name is Damián Pumar
http://www.damianpumar.com/

## Why do you want to join the core team?
A few days ago I was reading on medium and I saw your post, It's interesting Nimble's architecture, and I'd like to help you to improve and maintain it, I think that we have a lot of things to do here like a 

- Starter kit like a CRA
- Improve code and folder structure
- Add unit tests and test libraries
- Add examples and documentation for deverlopers

## Why should we let you join?
I have more than 12 years developing applications and also contributing to several open source projects.
I have many ideas that might help to improve this library.

## As a future core member, how confident do you feel about helping enforce the [Code of Conduct](https://github.com/nimble-ui/community/blob/main/CODE_OF_CONDUCT.md)?
That's great!

**Comment by IRod22** [comment]
@damianpumar You have been invited to join this Organization. Once you accept the invite, I would like you to go to the `virtual-hq` repository, then to Discussions. There should be a meeting in session.

Closing this issue.
